---
- name: arch-on-air hack playbook
  hosts: arch
  vars:
    ci: false
    full: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: additional developer tools
      pacman:
        state: present
        update_cache: false
        name:
          - binutils
          - gettext
          - flex
          - bison
          - clang
          - llvm
          - lldb
          - bpf
          - valgrind
          - dtc
          - patch
          - m4
          - autoconf
          - automake
          - pkgconf
          - asciidoc
          - libtool
          - pahole
          - yarn
          - cpanminus
          - cscope
          - yasm
          - clisp
          - wabt
          - cmake
          - cereal
          - gtest
          - numactl
          - fakeroot
          - unzip
          - jq
          - capnproto
          - flatbuffers
          - postgresql
          - postgresql-libs
          - mariadb-clients
          - jdk-openjdk
          - maven
          - librdkafka
          - redis
          - terraform
      become: true

    # https://wiki.archlinux.org/index.php/improving_performance
    - name: install perf tools!
      pacman:
        state: present
        update_cache: false
        name:
          - time
          - perf
          - iputils
          - netperf
          - iperf3
          - stress
          - sysstat
          - sysbench
          - sysdig
          - fio
          - iotop
          - hyperfine
          - bcc
          - bcc-tools
      become: true

    # https://rust-embedded.github.io/book/intro/install/linux.html
    - name: cross compile environment
      pacman:
        state: present
        update_cache: false
        name:
          - arm-none-eabi-gdb
          - qemu-headless-arch-extra
          - openocd
      become: true

    - name: metrics with prometheus
      pacman:
        state: present
        update_cache: false
        name:
          - prometheus
          - prometheus-node-exporter
          - alertmanager
      become: true

    - name: add user to postgres group
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: postgres
      become: true
      when: not ci|bool

    - name: install the latest perl packages
      import_tasks: tasks/perl.yaml
      when: not ci|bool

    - name: install the latest python packages
      import_tasks: tasks/python.yaml

    - name: create git and src directories for having fun
      file: path={{ lookup('env', 'HOME') }}/{{ item }} state=directory mode=0700
      with_items:
        - git
        - src

    - name: install the latest golang
      import_tasks: tasks/golang.yaml

    - name: install golang tools
      import_tasks: tasks/gopkg.yaml

    - name: install helm
      import_tasks: tasks/helm.yaml

    - name: install liburing, generic kernel I/O interface
      import_tasks: tasks/liburing.yaml

    - name: install ftrace, kernel tracer
      import_tasks: tasks/ftrace.yaml

    - name: install bcc for BPF fun
      import_tasks: tasks/bcc.yaml

    - name: install bpftrace to trace anything
      import_tasks: tasks/bpftrace.yaml
      when: full|bool

    - name: install the latest asciinema
      import_tasks: tasks/asciinema.yaml
      when: full|bool

    - name: python2 for gcloud...
      pacman:
        state: present
        update_cache: false
        name:
          - python2
      become: true
      when: full|bool

    - name: install the latest gcloud
      import_tasks: tasks/gcloud.yaml
      when: full|bool

    - name: install tendermint
      import_tasks: tasks/tendermint.yaml
      when: full|bool

    - name: install the latest ansible
      import_tasks: tasks/ansible.yaml
      when: full|bool and not ci|bool

    # https://github.com/rust-lang/rust#building-on-nix
    - name: install the latest rust
      import_tasks: tasks/rust.yaml
      when: full|bool and not ci|bool

    - name: install the latest protobuf
      import_tasks: tasks/protobuf.yaml
      when: full|bool and not ci|bool

    - name: install the latest terraform
      import_tasks: tasks/terraform.yaml
      when: full|bool and not ci|bool
